version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: digicsc-postgres
    environment:
      POSTGRES_USER: digicsc
      POSTGRES_PASSWORD: digicsc_password
      POSTGRES_DB: digicsc_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db-data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U digicsc"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: digicsc-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: digicsc
      MONGO_INITDB_ROOT_PASSWORD: digicsc_password
    ports:
      - "27017:27017"
    volumes:
      - ./docker/db-data/mongo:/data/db
    restart: unless-stopped
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u digicsc -p digicsc_password --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: digicsc-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-data:/data
    restart: always