"""Initial migration

Revision ID: b5cf2823e78d
Revises: 
Create Date: 2025-05-11 02:45:56.057920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cf2823e78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.Enum('CUSTOMER', 'FREELANCER', name='usertype'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('csc_id', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.Enum('HINDI', 'ENGLISH', 'KUMAONI', 'GHARWALI', name='language'), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('freelancer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_requests_freelancer_id'), 'freelancer_requests', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_freelancer_requests_id'), 'freelancer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_freelancer_requests_user_id'), 'freelancer_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freelancer_requests_user_id'), table_name='freelancer_requests')
    op.drop_index(op.f('ix_freelancer_requests_id'), table_name='freelancer_requests')
    op.drop_index(op.f('ix_freelancer_requests_freelancer_id'), table_name='freelancer_requests')
    op.drop_table('freelancer_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
